---
name: 'app-service-configurable'
version: '3.1.0'
releaseName: 'napa'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: 'fe79c06bffd29ecdd39921b37db4c05fa478f287'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64