---
name: 'app-service-configurable'
version: '4.0.1'
releaseName: 'odessa'
releaseStream: 'odessa'
lts: true
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: '2585b12695b756e2f486d4adeee72f01bb083840'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64