---
name: 'app-service-configurable'
version: '4.0.0'
releaseName: 'odessa'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: 'e952aefcdda7939f65187319d5e25fb8b4314498'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64