---
name: 'app-service-configurable'
version: '3.0.0'
releaseName: 'minnesota'
releaseStream: 'main'
lts: false
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: '162d3a06d6a77858f9267e44f258c8258eccc8be'
gitTag: true
dockerForce: false
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64