---
name: 'app-service-configurable'
version: '2.1.2'
releaseName: 'jakarta'
releaseStream: 'jakarta'
lts: true
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: 'c9a7dba17a903efbf39ab13b10ad13ffbdf09964'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64