---
name: 'go-mod-configuration'
version: '3.1.0'
releaseName: 'napa'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: '331853c130345ff2df93bd4439588ce2c3109fba'
gitTag: true
dockerImages: false