---
name: 'go-mod-configuration'
version: '4.0.1'
releaseName: 'odessa'
releaseStream: 'odessa'
lts: true
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: '0cec328f1d6dcc04feacfc8f3657d2a43ec09eb1'
gitTag: true
dockerImages: false