---
name: 'go-mod-configuration'
version: '2.3.0'
releaseName: 'levski'
releaseStream: 'main'
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: '696719805f16fdb1f1dabd114fa1cfb88149d110'
gitTag: true
dockerImages: false