---
name: 'go-mod-configuration'
version: '3.0.0'
releaseName: 'minnesota'
releaseStream: 'main'
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: '4d8d54a65c49840dae70675416d78ca62ff94528'
gitTag: true
dockerImages: false