---
name: 'go-mod-configuration'
version: '4.0.0'
releaseName: 'odessa'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: 'f245db316763ef41f589ea9965a2c2917ca9c256'
gitTag: true
dockerImages: false